### PR TITLE
Bump to 1.8.11

### PR DESCRIPTION
**Pull request by A6GibKm**
- Update freedesktop runtime to 19.08
- Update openjdk to openjdk11
- Updated various modules
- Builds only on 64 bits

I need to fix the arm build. It 64bit build is working but throwing console errors. 
TODO reoder modules.

### CODE REVIEW

**Comment by A6GibKm** [comment]
Fixes #9, the appdata file is fixed upstream.

**Comment by A6GibKm** [comment]
bot, build cc.arduino.arduinoide

**Comment by A6GibKm** [comment]
I can confirm that only one of my machines throws errors and it seems safe to ignore. I consider this is fine to merge after someone with more experience reviews it.

**Comment by A6GibKm** [comment]
The error I get is
```
java.lang.Exception: Error downloading https://downloads.arduino.cc/packages/package_index.json
	at cc.arduino.contributions.DownloadableContributionsDownloader.download(DownloadableContributionsDownloader.java:144) ~[arduino-core.jar:?]
	at cc.arduino.contributions.DownloadableContributionsDownloader.downloadIndexAndSignature(DownloadableContributionsDownloader.java:160) ~[arduino-core.jar:?]
	at cc.arduino.contributions.packages.ContributionInstaller.updateIndex(ContributionInstaller.java:306) ~[arduino-core.jar:?]
	at cc.arduino.contributions.packages.ui.ContributionManagerUI.lambda$onUpdatePressed$1(ContributionManagerUI.java:146) ~[pde.jar:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: javax.net.ssl.SSLException: Unexpected error: ...
```

**Comment by A6GibKm** [comment]
It seems it is missing a ca-certificate.

**Comment by A6GibKm** [comment]
I am having issues uploading to my Arduino, any help would be appreciated.

**Comment by merwok** [comment]
bot, build cc.arduino.arduinoide

**Comment by A6GibKm** [comment]
I pushed everything into a single commit. 

- Update Arduino ide to 1.8.11
- Update Freedesktop Sdk to 19.08
- Update openjdk to openjdk11
- Update modules
- Updated arduino-appdata-fixes.patch

Successfully Tested: 
- Update/Install libraries
- Flash AnalogReadSerial to an Arduino Uno
- Serial Monitor

As far as I can tell, it is working fine.

**Comment by A6GibKm** [comment]
@nedrichards @cosimoc does this package has a maintainer? I am willing to wring updates to it.

**Comment by A6GibKm** [comment]
@barthalion

**Pull request merged**
