### PR TITLE
Add Beta branch for arduino 2.0

### PR DESCRIPTION
**Pull request by joshuag1000**
THIS NEEDS CHECKING AND PEER REVIEWING

I have been able to create a flatpak for v2. 
To get the new version to run i had to disable the chrome sandbox (not sure if this will cause issues or not)
~~I haven't tested uploading any scripts yet or many main functions of arduino itself.~~
I also didn't include any libraries into the flatpak like on the current branch (Edit: i personally didn't see them necessary, as libraries (and more) can be added in the sketchbook folder or are already included with the editor. It also helps keep the download lighter as the new version is quite large).
**Obviously this needs committing into a beta branch which i couldn't select as there isn't one.**

I ~~will do some more testing later~~ have done some testing ~~(and fixes if needed)~~ but i would like to share my work.  
Edit: Update posted see [this comment](https://github.com/flathub/cc.arduino.arduinoide/pull/42#issuecomment-1033992885).

Addresses issue #29

Allow edits by maintainers is on.

### CODE REVIEW

**Comment by A6GibKm** [comment]
Thanks for your contribution. Looks interesting, Ill check it during the week.

Since this is a new app, it might make sense to have it in a separate repository.

**Comment by A6GibKm** [comment]
> > Thanks for your contribution. Looks interesting, Ill check it during the week.
> > Since this is a new app, it might make sense to have it in a separate repository.
> 
> Yeah I agree with you on this however I have never published a new app on flathub before I have only contributed. Should you choose to do that I'm willing to help and contribute with that.

If we choose this direction I can take care of the *process* so don't worry about it.

**Comment by joshuag1000** [comment]
> > > Thanks for your contribution. Looks interesting, Ill check it during the week.
> > > Since this is a new app, it might make sense to have it in a separate repository.
> > 
> > Yeah I agree with you on this however I have never published a new app on flathub before I have only contributed. Should you choose to do that I'm willing to help and contribute with that.
> 
> If we choose this direction I can take care of the *process* so don't worry about it.

Makes sense.

**Comment by joshuag1000** [comment]
I'd just thought i'd update here and say that after some further testing (compiling and uploading code, using libraries saved in my sketchbook, signing into my arduino account inside the app) everything seems to be working as expected (i.e. a bug or two i hit was not flatpaks fault but a bug in the editor because of its release candidate state if that makes sense).
For obvious reasons i still recommend that others do some testing but i'd thought id share my results here.

**Comment by per1234** [comment]
>I also didn't include any libraries into the flatpak like on the current branch

Unlike Arduino IDE 1.x, which bundles them in the installation, Arduino IDE 2.x [automatically installs the fundamental libraries](https://github.com/arduino/arduino-ide/pull/663) (e.g., Keyboard, Mouse, Servo) [as well as the "Arduino AVR Boards" platform](https://github.com/arduino/arduino-ide/pull/497) on the first run.

**Comment by joshuag1000** [comment]
> > I also didn't include any libraries into the flatpak like on the current branch
> 
> Unlike Arduino IDE 1.x, which bundles them in the installation, Arduino IDE 2.x [automatically installs the fundamental libraries](https://github.com/arduino/arduino-ide/pull/663) (e.g., Keyboard, Mouse, Servo) [as well as the "Arduino AVR Boards" platform](https://github.com/arduino/arduino-ide/pull/497) on the first run.

Good to know i didnt include anything that wasn't needed.

**Comment by joshuag1000** [comment]
bot, build

**Comment by A6GibKm** [comment]
The source of the new ide is not available?

**Comment by joshuag1000** [comment]
> The source of the new ide is not available?

it is why do you ask?

**Comment by A6GibKm** [comment]
bot, build

**Comment by A6GibKm** [comment]
>  To get the new version to run i had to disable the chrome sandbox (not sure if this will cause issues or not)

Please use [zypak](https://github.com/refi64/zypak), see https://github.com/flathub/com.discordapp.Discord/blob/master/com.discordapp.Discord.json for example,

**Comment by joshuag1000** [comment]
> > > The source of the new ide is not available?
> > 
> > 
> > It is why do you ask? Edit: https://github.com/arduino/arduino-ide
> 
> Because in an ideal world we build it from source instead of downloading a binary at runtime.

yeah I agree this would be ideal but i haven't much experience with compiling from source in electron but i am seeing what i can do in the background

**Comment by per1234** [comment]
@joshuag1000 there is documentation here:
https://github.com/arduino/arduino-ide/blob/main/BUILDING.md

You can open issues at https://github.com/arduino/arduino-ide/issues if you discover any errors or have suggestions for improvements.

**Comment by joshuag1000** [comment]
> @joshuag1000 there is documentation here: https://github.com/arduino/arduino-ide/blob/main/BUILDING.md
> 
> You can open issues at https://github.com/arduino/arduino-ide/issues if you discover any errors or have suggestions for improvements.

yeah i saw that while building the flatpak. I ran into issues building though because fedora ships node v16 which didn't work very well. i am looking into compiling the ide from source but i didn't see it as essential for now.

**Comment by joshuag1000** [comment]
Just thought i'd update.
I'm having some difficulty getting zypak to work with the arduino application. Whenever i attempt to run the application with zypak nothing happens and nothing appears in the console.

As for compiling from source i am also having some difficulties here. I am able to get the application to compile and package arduino but it crashes when I attempt to run the application. 

```
Starting backend process. PID: 15
/app/arduino-ide/resources/app/node_modules/bindings/bindings.js:121
        throw e;
        ^

Error: /app/arduino-ide/resources/app/node_modules/drivelist/build/Release/drivelist.node: undefined symbol: _ZN2v816FunctionTemplate3NewEPNS_7IsolateEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEENS_5LocalIS4_EENSA_INS_9SignatureEEEiNS_19ConstructorBehaviorENS_14SideEffectTypeE
    at process.func [as dlopen] (electron/js2c/asar.js:140:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1034:18)
    at Object.func [as .node] (electron/js2c/asar.js:140:31)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at bindings (/app/arduino-ide/resources/app/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/app/arduino-ide/resources/app/node_modules/drivelist/js/index.js:25:27)
```

I suspect this is due to me compiling it incorrectly or something is not compiling correctly while in the environment, but I will keep working on this as best as i can to see if i can get it to work.
If you want to see if you can work out where i went wrong I'm keeping my latest work for the compile here: https://github.com/joshuag1000/cc.arduino.arduinoide/tree/Beta-Compile

The latest commit i made (https://github.com/joshuag1000/cc.arduino.arduinoide/commit/0d48e72cfcc49fd3d0c277a405c77664c100ac82) it just some tiding i made to the json file to improve the install.

**Comment by joshuag1000** [comment]
bot, build

**Comment by joshuag1000** [comment]
bot, build

**Comment by joshuag1000** [comment]
I have been thinking about this: 

> Thanks for your contribution. Looks interesting, Ill check it during the week.
> 
> Since this is a new app, it might make sense to have it in a separate repository.

I'm thinking that is would be a good idea to create a new repository/app for the new version as there is a huge difference between the 2 versions and some people may want to use the old version.
What are your thoughts? I'm willing to handle the creation etc but i just wanted your opinion about this (if that makes any sense).

**Comment by A6GibKm** [comment]
> I'm thinking that is would be a good idea to create a new repository/app for the new version as there is a huge difference between the 2 versions and some people may want to use the old version.
What are your thoughts? I'm willing to handle the creation etc but i just wanted your opinion about this (if that makes any sense).

I think it is the best option. If at some point the current Arduino app becomes deprecated we can wait a bit and then deprecate this repo (pointing to the new one).

> Also in case you missed i was recently able to get zypak working properly meaning that the package isn't using the --no-sandbox parameter.
I have been working on building from source but im having issues and the default build instructions aren't working/neither are the ones used in the nightly builds. And the fact that i dont have huge experience with compiling Electron/theia apps is slowing me down. I'll get it eventually but i dont have much free time now until july to look into it but for now downloading the pre-compiled binary works just fine and compiling from source is just an ideal.

Great, zypark is the only way atm to make electron apps work sandboxed. Yes building electron apps from source is hard and not something I can really help you with but I can ask around, we can start like this when submitting it. Do you have any idea when the app is going to be released? I see it is at rc6.

Another thing to check is whether the repository upstream counts with the app icon, desktop file and metainfo/appdata so to use those instead.

**Comment by joshuag1000** [comment]
> 

The icon i pulled from within the build so i'll update the build commands to get it from there, i dont think they have a desktop file or metainfo file in the repo/builds yet but i will check

**Comment by joshuag1000** [comment]
i am closing this pr as the v2 ide has been created as a separate flathub app.
thanks to those who helped with this.

**Comment by A6GibKm** [comment]
Congratulations and thanks for looking into it!

**Comment by joshuag1000** [comment]
https://github.com/arduino/arduino-ide/issues/1001

**Comment by joshuag1000** [comment]
Yeah i reached out just to check to see if was ok. if they want to take over or contribute im obviously fine with that

**Pull request closed without merging**
