### PR TITLE
Remove retired libraries

### PR DESCRIPTION
**Pull request by joshuag1000**
Just a suggestion really. But these 3 libraries have been retired by Arduino and havent been updated in 4 years.
Are these still needed to be included?

### CODE REVIEW

**Comment by joshuag1000** [comment]
bot, build

**Review by per1234 — COMMENTED** [review]
My opinion is that it is best for the package to mirror the official IDE distribution as closely as possible.

However, it is true that some of these libraries are not so relevant anymore, especially considering how easy it is to install them on demand via the Arduino IDE Library Manager.

If you compare the list of libraries distributed with Arduino IDE 1.x to the ones installed on first run of 2.x, you can see some were removed during the transition to the new system:

https://github.com/arduino-libraries/Arduino_BuiltIn/blob/main/library.properties#L10

**Comment by A6GibKm** [comment]
Every time I updated arduino I just add whatever is missing for it to build, naturally I never considered looking into what stuff is no longer required.

**Comment by joshuag1000** [comment]
> My opinion is that it is best for the package to mirror the official IDE distribution as closely as possible.
> 
> However, it is true that some of these libraries are not so relevant anymore, especially considering how easy it is to install them on demand via the Arduino IDE Library Manager.
> 
> If you compare the list of libraries distributed with Arduino IDE 1.x to the ones installed on first run of 2.x, you can see some were removed during the transition to the new system:
> 
> https://github.com/arduino-libraries/Arduino_BuiltIn/blob/main/library.properties#L10

That builtin library works but it hasnt been updated in a while but i will add TFT back as it is apparently required/included by IDE v1

**Comment by A6GibKm** [comment]
> My opinion is that it is best for the package to mirror the official IDE distribution as closely as possible.
> 
> However, it is true that some of these libraries are not so relevant anymore, especially considering how easy it is to install them on demand via the Arduino IDE Library Manager.
> 
> If you compare the list of libraries distributed with Arduino IDE 1.x to the ones installed on first run of 2.x, you can see some were removed during the transition to the new system:
> 
> https://github.com/arduino-libraries/Arduino_BuiltIn/blob/main/library.properties#L10

Agreed 100%, but note that I do not have the time to keep track of all changes upstream. Contributions like this are enormously welcomed and I can certainly help/guide anyone interested in helping.

**Comment by joshuag1000** [comment]
> > My opinion is that it is best for the package to mirror the official IDE distribution as closely as possible.
> > However, it is true that some of these libraries are not so relevant anymore, especially considering how easy it is to install them on demand via the Arduino IDE Library Manager.
> > If you compare the list of libraries distributed with Arduino IDE 1.x to the ones installed on first run of 2.x, you can see some were removed during the transition to the new system:
> > https://github.com/arduino-libraries/Arduino_BuiltIn/blob/main/library.properties#L10
> 
> Agreed 100%, but note that I do not have the time to keep track of all changes upstream. Contributions like this are enormously welcomed and I can certainly help/guide anyone interested in helping.

I can fully understand that. Maintaining all those libraries would be alot. This is just a one time contribution. If i get time i might create another pr updating any libraries if they need it but again that would just be a one time contribution as i dont have the time to take on keeping all of these libraries up to date 24/7.

**Comment by per1234** [comment]
>That builtin library works but it hasnt been updated in a while

There is no reason to update it. It only serves as a "shell" to define the list of libraries that should be installed on first run of the Arduino IDE 2.x, or any other Arduino development tool which wants to provide the collection of libraries the users will expect to have available by default.

If Arduino decides that list of libraries should change, it will be updated. Otherwise, nothing needs to be done. It works perfectly as it is.

>note that I do not have the time to keep track of all changes upstream.

I don't expect there will be many to keep track of. The development effort is focused on Arduino IDE 2.x.

Anyway, I don't see how that is relevant. The least maintenance effort will be achieved by mirroring the project you are packaging. Any divergences will only increase the maintenance effort because you will need to reconcile the arbitrary changes made to your package with the upstream project.

**Comment by joshuag1000** [comment]
Im going to close this pr as it appears the build script for arduino wants them so its probably best we leave them in even though they are retired and can be manually removed by the user.

**Comment by per1234** [comment]
There is a "light_bundle" build option:

https://github.com/arduino/Arduino/blob/1.8.19/build/build.xml#L254

But that is not so granular as what is wanted here.

**Comment by joshuag1000** [comment]
> There is a "light_bundle" build option:
> 
> https://github.com/arduino/Arduino/blob/1.8.19/build/build.xml#L254
> 
> But that is not so granular as what is wanted here.

maybe but its probably best we try to keep the flatpak build as close to the original build as possible

**Comment by A6GibKm** [comment]
if the default build option wants those libs, then we want them here. Thanks for looking into it.

**Pull request closed without merging**
